### ISSUE TITLE
Book Allocation Problem

### ISSUE THREAD

**Issue by tanishgoyal07** [Ayushlath/Coding-Solution-from-different-plateforms-Hacktoberfest2K22#12]
I want to add code solution for Book Allocation Problem in cpp

**Comment by tanishgoyal07** [comment]
@Ayushlath please assign this issue to me

**Comment by Ayushlath** [comment]
fork this project then you can add the file in the forked one and create pull request for same.
Don't forget to include T.C and S.C

**Comment by tanishgoyal07** [comment]
@Ayushlath okay will do that . Are you assigning this to me???
